site_name: The Broom Wiki
theme:
  name: material
  logo: assets/logo.jpg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - search.suggest
    - search.share
    - navigation.footer

nav:
  - Home: index.md
  - Docs:
    - Style guide: styleguide.md
    - Safety Form: safety.md
    - Podcast: podcast.md
    - Mastodon: mastodon.md
  - HodaPage: hodapage.md    
  - Blog:
    - blog/index.md

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - search
  - blog:
    blog_dir: blog
  - glightbox
  - social

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://m.thebroom.us/@radio
    - icon: fontawesome/brands/github
      link: https://github.com/The-Broom-Radio
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/thebroomradio
copyright: Copyright 2024 The Broom