authors:
  podrock:
    name: podrock
    description: Network Dude
    avatar: https://github.com/podrock.png
  hoda:
    name: Intrepidbodies
    description: TheBombDotCom
    avatar: https://github.com/intrepidbodies.png